spring.application.name=spring_solid_criteria
server.port=${SERVER_PORT:8012}

# Logging
logging.config=classpath:logback-spring.xml

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# server.port=${SERVER_PORT:8012}
# spring.profiles.active=prod
# spring.application.name=spring_solid_criteria

# spring.datasource.url=jdbc:mysql://localhost:3306/mydb
# spring.datasource.username=user
# spring.datasource.password=password
# # Use 'none' to avoid auto schema generation, or 'update' if you want Hibernate to manage schema updates
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# spring.datasource.hikari.minimum-idle=5
# spring.datasource.hikari.maximum-pool-size=20
# spring.datasource.hikari.idle-timeout=30000
# spring.datasource.hikari.connection-timeout=20000
# spring.datasource.hikari.max-lifetime=1800000

# logging.config=classpath:logback-spring.xml

# # Liquibase
# spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
# spring.liquibase.enabled=true

# # consul (if running witout docker you can set consul.enabled to false and consul.discovery.enabled to false)
# spring.cloud.consul.enabled=false
# spring.cloud.consul.discovery.enabled=false

